dist: trusty
language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.3
    - php: 7.3
    - php: 7.4
    - php: 8.0

install:
  - composer update --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
