name: Export data

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'resources/**'

jobs:
  update:
    runs-on: ubuntu-22.04

    name: Generate coef exports in /data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Prepare autoload
        run: composer dump-autoload

      - name: Generate JSON exports
        run: php bin/prepare_json.php

      - name: Generate WA CSV exports
        run: php bin/prepare_wa_csv.php

      - name: Generate Combined CSV exports
        run: php bin/prepare_combined_csv.php

      - name: Generate Classifier CSV exports
        run: php bin/prepare_classifier_csv.php

      - name: Generate Youthguard CSV exports
        run: php bin/prepare_youthguard_csv.php

      - name: Commit coef exports
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update coef exports
          file_pattern: data/
