name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          working_dir: ./src

      - name: Run tests
        run: composer test